version: '3'

services:

  web_app:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - web_network
      - db_network  # <-- connect to the bridge
    depends_on:  # <-- wait for db to be "ready" before starting the app
      - db

  web:
    image: nginx:latest
    ports:
      - 82:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    depends_on:
      - web_app
    networks:
      - web_network

  db:  # <-- IMPORTANT: same name as in DATABASES setting, otherwise Django won't find the database!
    image: postgres:11
    env_file:  # <-- we use the previously defined values
      - config/db/db_env
    networks:  # <-- connect to the bridge
      - db_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  db_web:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - db_webs:/root/.pgadmin
    ports:
      - 5055:80
    networks:
      - db_network
    restart: unless-stopped
    logging:
      driver: none

networks:
  web_network:
    driver: bridge
  db_network:  # <-- add the bridge
    driver: bridge

volumes:
  db_volume:
  db_webs:
  static_volume:
  media_volume:
