# Generated by Django 2.1.4 on 2019-03-10 05:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(default=datetime.datetime(2019, 3, 10, 5, 7, 49, 711333, tzinfo=utc))),
                ('picture', models.ImageField(upload_to='images/news')),
                ('content', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminEmail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
