# Generated by Django 2.1.4 on 2019-03-10 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190310_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 8, 49, 32, 313832, tzinfo=utc)),
        ),
    ]
