# Generated by Django 2.1.4 on 2019-01-08 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181231_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='dateUpdate',
        ),
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 8, 13, 32, 548187, tzinfo=utc)),
        ),
    ]
