# Generated by Django 2.1.4 on 2019-03-10 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190310_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 9, 1, 12, 393426, tzinfo=utc)),
        ),
    ]
