# Generated by Django 2.1.4 on 2019-01-09 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190109_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 11, 40, 46, 660119, tzinfo=utc)),
        ),
    ]
