# Generated by Django 2.1.4 on 2019-03-26 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190310_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 6, 1, 45, 643249, tzinfo=utc)),
        ),
    ]
