# Generated by Django 2.1.4 on 2019-01-17 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190117_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 5, 49, 41, 512306, tzinfo=utc)),
        ),
    ]
