# Generated by Django 2.1.4 on 2019-01-30 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190120_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 17, 44, 1, 81412, tzinfo=utc)),
        ),
    ]
