# Generated by Django 2.1.4 on 2019-02-03 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190130_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 4, 20, 35, 480306, tzinfo=utc)),
        ),
    ]
