# Generated by Django 2.1.4 on 2019-02-05 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20190203_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 7, 21, 40, 661269, tzinfo=utc)),
        ),
    ]
