# Generated by Django 2.1.4 on 2019-02-05 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190205_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 7, 22, 54, 927484, tzinfo=utc)),
        ),
    ]
