# Generated by Django 2.1.4 on 2019-01-10 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190109_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 8, 35, 54, 563305, tzinfo=utc)),
        ),
    ]
