# Generated by Django 2.1.4 on 2019-01-10 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190110_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 8, 36, 6, 997951, tzinfo=utc)),
        ),
    ]
