# Generated by Django 2.1.5 on 2019-01-20 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190117_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 5, 59, 13, 145288, tzinfo=utc)),
        ),
    ]
