# Generated by Django 2.1.4 on 2019-03-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aims_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Aim',
        ),
        migrations.RenameModel(
            old_name='Aims',
            new_name='Event',
        ),
    ]
