# Generated by Django 2.1.4 on 2019-03-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190310_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Service',
        ),
    ]
