# Generated by Django 2.1.4 on 2019-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190130_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
